apiVersion: v1
kind: Service
metadata:
  name: resqnet-service
  namespace: resqnet
  labels:
    app: resqnet
spec:
  selector:
    app: resqnet
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
